import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { fmt, fmtTime, fmtInt } from '../../utils/helpers.js';
import { FileDown } from 'lucide-react';

export default function PdfExport({ config, results }) {
    const generate = () => {
        if (!results) return;

        const doc = new jsPDF();
        const pageWidth = doc.internal.pageSize.getWidth();

        // Title
        doc.setFontSize(18);
        doc.setTextColor(40, 40, 40);
        doc.text('Drone Performance Report', pageWidth / 2, 20, { align: 'center' });

        doc.setFontSize(9);
        doc.setTextColor(120, 120, 120);
        doc.text(`Generated: ${new Date().toLocaleString()}`, pageWidth / 2, 27, { align: 'center' });

        let y = 35;

        // Configuration table
        doc.setFontSize(12);
        doc.setTextColor(40, 40, 40);
        doc.text('Configuration', 14, y);
        y += 5;

        autoTable(doc, {
            startY: y,
            head: [['Parameter', 'Value']],
            body: [
                ['Motors', `${config.frame.motorCount}× (${config.frame.layout})`],
                ['Frame Weight', `${config.frame.frameWeight}g`],
                ['Payload', `${config.frame.payloadWeight}g`],
                ['Battery', `${config.battery.cellsS}S${config.battery.cellsP}P ${config.battery.capacityMah}mAh ${config.battery.chemistry}`],
                ['Motor Kv', `${config.motor.kv} RPM/V`],
                ['Motor Resistance', `${config.motor.resistance}Ω`],
                ['Propeller', `${config.propeller.diameterIn}×${config.propeller.pitchIn} ${config.propeller.blades}-blade`],
                ['Altitude', `${config.environment.altitude}m`],
                ['Temperature', `${config.environment.temperature}°C`],
            ],
            theme: 'grid',
            styles: { fontSize: 9 },
            headStyles: { fillColor: [74, 158, 255] },
        });

        y = doc.lastAutoTable.finalY + 10;

        // Results table
        doc.setFontSize(12);
        doc.text('Performance Results', 14, y);
        y += 5;

        autoTable(doc, {
            startY: y,
            head: [['Metric', 'Value', 'Status']],
            body: [
                ['Total Weight', `${fmtInt(results.totalWeightG)}g`, ''],
                ['Hover Time', fmtTime(results.flightTimeMin), results.hoverThrottle < 60 ? '✓' : '⚠'],
                ['Hover Throttle', `${fmt(results.hoverThrottle)}%`, results.hoverThrottle < 60 ? '✓' : '⚠'],
                ['TWR', `${fmt(results.twr, 2)}:1`, results.twr >= 2 ? '✓' : '✗'],
                ['Max Thrust', `${fmtInt(results.maxTotalThrustG)}g`, ''],
                ['Max RPM', fmtInt(results.maxRPM), ''],
                ['Hover Current/Motor', `${fmt(results.hoverCurrentPerMotor)}A`, results.validations.motorCurrentOk ? '✓' : '✗'],
                ['Total Hover Power', `${fmt(results.hoverTotalPower, 0)}W`, ''],
                ['Hover Efficiency', `${fmt(results.hoverEfficiency)} g/W`, ''],
                ['Battery Voltage (hover)', `${fmt(results.hoverBatteryVoltage)}V`, ''],
                ['Voltage Sag', `${fmt(results.hoverBatterySag)}V`, ''],
                ['Motor Temp (5min)', `${fmt(results.motorTemp5min, 0)}°C`, results.validations.motorTempOk ? '✓' : '✗'],
                ['Wire Power Loss', `${fmt(results.totalWireLoss)}W`, ''],
            ],
            theme: 'grid',
            styles: { fontSize: 9 },
            headStyles: { fillColor: [74, 158, 255] },
        });

        y = doc.lastAutoTable.finalY + 10;

        // Validation
        doc.setFontSize(12);
        doc.text('Safety Validation', 14, y);
        y += 5;

        const v = results.validations;
        autoTable(doc, {
            startY: y,
            head: [['Check', 'Status']],
            body: [
                ['Motor current within limit', v.motorCurrentOk ? 'PASS' : 'FAIL'],
                ['ESC current within limit', v.escCurrentOk ? 'PASS' : 'FAIL'],
                ['Battery discharge < C-rating', v.batteryDischargeOk ? 'PASS' : 'FAIL'],
                ['TWR ≥ 2.0', v.twrOk ? 'PASS' : 'FAIL'],
                ['Motor temp < 80°C', v.motorTempOk ? 'PASS' : 'FAIL'],
                ['Hover throttle < 60%', v.hoverThrottleOk ? 'PASS' : 'FAIL'],
            ],
            theme: 'grid',
            styles: { fontSize: 9 },
            headStyles: { fillColor: [74, 158, 255] },
            didParseCell: (data) => {
                if (data.column.index === 1 && data.section === 'body') {
                    data.cell.styles.textColor = data.cell.raw === 'PASS' ? [52, 211, 153] : [248, 113, 113];
                    data.cell.styles.fontStyle = 'bold';
                }
            },
        });

        // Footer
        doc.setFontSize(8);
        doc.setTextColor(150, 150, 150);
        doc.text('Generated by DroneCalc — Estimates only, verify before flight.', pageWidth / 2, doc.internal.pageSize.getHeight() - 10, { align: 'center' });

        doc.save(`drone-report-${Date.now()}.pdf`);
    };

    return (
        <button className="btn btn-secondary" onClick={generate} disabled={!results}>
            <FileDown size={14} /> Export PDF
        </button>
    );
}
